# -*- coding: utf-8 -*-
"""coding_exercise_ml_basics

Automatically generated by Colab.

"""

## **QUESTION 1

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, r2_score
# Generate sample data
# Used to load the Ames housing dataset that will be used to train the model and run tests
df = pd.read_csv("ames_house_prices.csv", na_values="?")

df = df[["GrLivArea", "Neighborhood", "SalePrice"]]

df = df.rename(columns={
    "GrLivArea": "square_footage",
    "Neighborhood": "location",
    "SalePrice": "price"
})
# remove rows that are missing values, for the most conslusive data possible
df = df.dropna(
    subset=["square_footage", "location", "price"]
)

print("Number of house records:", len(df))
print(df.head())

# To allow the notebook to proceed without error, I will temporarily create a dummy DataFrame.
# You will need to replace this with your actual data loading and preprocessing.

# Features and target
# x has the features that are used to predict/ y has the house predicts we're trying to predict
X = df[['square_footage', 'location']]
y = df['price']
# Preprocessing: One-hot encode the location column
preprocessor = ColumnTransformer(
transformers=[
('location', OneHotEncoder(
    drop="first",
    handle_unknown="ignore",
    sparse_output=False
), ['location'])
], remainder='passthrough')
# Create pipeline with preprocessing and model
model = Pipeline(steps=[
('preprocessor', preprocessor),
('regressor', LinearRegression())
])
# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)
# Train model
model.fit(X_train, y_train)
test_predictions = model.predict(X_test)

mae = mean_absolute_error(y_test, test_predictions)
r2 = r2_score(y_test, test_predictions)

print(f"\nMean Absolute Error: ${mae:,.2f}")
print(f"R-squared: {r2:.3f}")
# Make prediction for a new house: 2000 sq ft in Downtown
new_house = pd.DataFrame({'square_footage': [2000], 'location': ['OldTown']})
predicted_price = model.predict(new_house)

print(f"Predicted price for a 2000 sq ft house in OldTown: "
f"${predicted_price[0]:,.2f}"
)
# Display model coefficients
feature_names = (model.named_steps['preprocessor']
.named_transformers_['location']
.get_feature_names_out(['location'])).tolist() + \
['square_footage']
coefficients = model.named_steps['regressor'].coef_
print("\nModel Coefficients:")
for feature, coef in zip(feature_names, coefficients):
  print(f"{feature}: {coef:.2f}")

## **QUESTION 2

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
# Evaluation metrics added
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)
# Generate sample customer data
df = pd.read_csv("iranian_churn.csv")

df.columns = [" ".join(column.split()) for column in df.columns]

print("Number of customer records:", len(df))
print(df.head())
# Features and target
numerical_features = [
    "Age",
    "Subscription Length",
    "Seconds of Use",
    "Frequency of use",
    "Customer Value",
    "Call Failure",
    "Complains"
]
categorical_features = [
    "Tariff Plan",
    "Status"
]

features = numerical_features + categorical_features

df = df.dropna(subset=features + ["Churn"])
df["Churn"] = df["Churn"].astype(int)
df[categorical_features] = df[categorical_features].astype(str)

X = df[features]
y = df["Churn"]

# Preprocessing: Scale numerical features and one-hot encode categorical features
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features
        ),
        (
            "cat",
            OneHotEncoder(
                drop="first",
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_features
        )
    ]
)
# Create pipeline with preprocessing and model
model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    (
        "classifier",
        LogisticRegression(
            random_state=42,
            max_iter=1000
        )
    )
])

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42, stratify=y)
# Train model
model.fit(X_train, y_train)
test_predictions = model.predict(X_test)

accuracy = accuracy_score(
    y_test,
    test_predictions
)

precision = precision_score(
    y_test,
    test_predictions,
    zero_division=0
)

recall = recall_score(
    y_test,
    test_predictions,
    zero_division=0
)

f1 = f1_score(
    y_test,
    test_predictions,
    zero_division=0
)

conf_matrix = confusion_matrix(
    y_test,
    test_predictions
)

print(f"\nModel Accuracy: {accuracy:.2%}")
print(f"Precision: {precision:.2%}")
print(f"Recall: {recall:.2%}")
print(f"F1 Score: {f1:.2%}")

print("Confusion Matrix:")
print(conf_matrix)

# Predict churn probability for a new customer
new_customer = pd.DataFrame({
    "Age": [35],
    "Subscription Length": [18],
    "Seconds of Use": [1200],
    "Frequency of use": [20],
    "Customer Value": [60],
    "Call Failure": [8],
    "Complains": [1],
    "Tariff Plan": ["1"],
    "Status": ["2"]
})
churn_probability = model.predict_proba(new_customer)[0][1]
# Probability of churn
# (class 1)
# Classify based on threshold (0.5)
threshold = 0.5
churn_prediction = 1 if churn_probability >= threshold else 0
print(f"Churn Probability for new customer: {churn_probability:.2f}")
print(f"Churn Prediction (1 = churn, 0 = no churn): {churn_prediction}")

print(
    "A probability of 50% or higher means the customer "
    "is classified as being at risk of leaving."
)

print(
    "The business could contact at-risk customers with "
    "customer service, a plan review, or a retention offer."
)
# Display model coefficients
feature_names = (
    model.named_steps["preprocessor"]
    .get_feature_names_out()
)

coefficients = (
    model.named_steps["classifier"]
    .coef_[0]
)

print("\nModel Coefficients:")
for feature, coef in zip(feature_names, coefficients):
    print(f"{feature}: {coef:.2f}")

## **QUESTION 3

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
# Generate sample customer data
df = pd.read_csv("wholesale_customers.csv")

print("Number of customer records:", len(df))
print(df.head())
# Preprocess data: Select numerical features and scale them
features = [
    "Fresh",
    "Milk",
    "Grocery",
    "Frozen",
    "Detergents_Paper",
    "Delicassen"
]

df = df.dropna(subset=features)

X = df[features]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
# Determine optimal number of clusters using elbow method

inertia = []
K = range(1, 6)

for k in K:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

print("Inertia values:")
for k, value in zip(K, inertia):
    print(f"K={k}: {value:.2f}")
# Plot elbow curve
plt.figure(figsize=(8, 5))
plt.plot(K, inertia, 'bo-')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal K')
plt.savefig('elbow_plot.png')
plt.show()
# Apply K-Means with optimal K (e.g., 3 based on elbow method)
## The inertia decreased a lot more through the first few clusters, but improvements were getting smaller over time after 3 clusters.
## 3 clusters was the random example, but after a bit of testing it was discovered to be the sweet spot.
optimal_k = 3
kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(X_scaled)
# Analyze clusters
cluster_summary = df.groupby('cluster')[features].mean().round(2)
print("Cluster Characteristics:")
print(cluster_summary)
# Example of targeted strategies
for cluster in range(optimal_k):
    print(f"\nCluster {cluster} Strategy:")

    if (
        cluster_summary.loc[cluster, "Fresh"]
        > cluster_summary.loc[cluster, "Grocery"]
    ):
        print(
            "Customers buy more fresh products. "
            "Offer fresh and frozen food packages for "
            "restaurants or food-service businesses."
        )
    else:
        print(
            "Customers buy more grocery products. "
            "Offer grocery and household product bundles "
            "with volume discounts."
        )

# Save cluster assignments to CSV
df.to_csv('customer_segments.csv', index=False)
